### ISSUE TITLE
worst project ever

### ISSUE THREAD

**Issue by xTrayambak** [ArnavPC/Enovators-Car#1]
my PC has turned into a nuclear bomb and is currently in the process of destroying NOIDA after attempting to compile drivers for this project
0/10

wher are the anime woemn i was promised!??!?????

very bad project

reporting it to ghituhb

**Comment by ArnavPC** [comment]
u want women???
i hereby give u
ANJALI SHRIVASTAV

**Comment by ArnavPC** [comment]
have fun

**Comment by xTrayambak** [comment]
probs should delete that lmao
